import type { WatchlistCategorySuggestion } from './trendWatchlistCategoryTree'

/** FR-164 种子目录：tsCode → 分类/赛道建议（只读） */
export const WATCHLIST_CATEGORY_CATALOG: Record<string, WatchlistCategorySuggestion[]> = {
  "000938.SZ": [{ category: "CPO", subCategory: "CPO交换机" }],
  "000977.SZ": [{ category: "AI算力", subCategory: "AI服务器" }],
  "002080.SZ": [{ category: "绿色能源（风电）", subCategory: "风电叶片" }],
  "002129.SZ": [{ category: "半导体材料", subCategory: "半导体硅片" }],
  "002156.SZ": [{ category: "半导体材料", subCategory: "先进封装（封测）" }],
  "002167.SZ": [{ category: "固态电池", subCategory: "氧化物电解质" }],
  "002202.SZ": [{ category: "绿色能源（风电）", subCategory: "风电整机" }],
  "002281.SZ": [{ category: "CPO", subCategory: "光器件" }],
  "002371.SZ": [{ category: "半导体设备", subCategory: "刻蚀设备" }, { category: "半导体设备", subCategory: "薄膜沉积设备" }],
  "002384.SZ": [{ category: "PCB", subCategory: "消费电子/FPC" }],
  "002436.SZ": [{ category: "半导体材料", subCategory: "测试板" }, { category: "PCB", subCategory: "IC封装基板" }],
  "002460.SZ": [{ category: "固态电池", subCategory: "固态电池（整体）" }, { category: "固态电池", subCategory: "硫化物电解质" }, { category: "能源金属", subCategory: "锂矿" }],
  "002463.SZ": [{ category: "PCB", subCategory: "通信/服务器PCB" }],
  "002466.SZ": [{ category: "能源金属", subCategory: "锂矿" }],
  "002594.SZ": [{ category: "储能", subCategory: "储能系统集成商" }],
  "002709.SZ": [{ category: "锂电池", subCategory: "电解液" }, { category: "固态电池", subCategory: "硫化物电解质" }],
  "002812.SZ": [{ category: "锂电池", subCategory: "隔膜" }, { category: "固态电池", subCategory: "固态电池隔膜" }],
  "002850.SZ": [{ category: "锂电池", subCategory: "结构件" }],
  "002913.SZ": [{ category: "PCB", subCategory: "显卡/新能源PCB" }],
  "002916.SZ": [{ category: "PCB", subCategory: "通信/服务器PCB" }, { category: "PCB", subCategory: "IC封装基板" }],
  "002938.SZ": [{ category: "PCB", subCategory: "消费电子/FPC" }],
  "300014.SZ": [{ category: "储能", subCategory: "储能电池" }],
  "300037.SZ": [{ category: "锂电池", subCategory: "电解液" }],
  "300054.SZ": [{ category: "半导体材料", subCategory: "CMP抛光材料" }],
  "300073.SZ": [{ category: "锂电池", subCategory: "三元材料正极" }],
  "300236.SZ": [{ category: "半导体材料", subCategory: "光刻胶（KrF/ArF高端）" }],
  "300274.SZ": [{ category: "储能", subCategory: "储能系统集成商" }],
  "300308.SZ": [{ category: "CPO", subCategory: "光模块" }],
  "300394.SZ": [{ category: "CPO", subCategory: "光器件" }],
  "300450.SZ": [{ category: "锂电池", subCategory: "锂电设备" }],
  "300457.SZ": [{ category: "锂电池", subCategory: "锂电设备" }],
  "300476.SZ": [{ category: "PCB", subCategory: "显卡/新能源PCB" }],
  "300502.SZ": [{ category: "CPO", subCategory: "光模块" }],
  "300568.SZ": [{ category: "锂电池", subCategory: "隔膜" }, { category: "固态电池", subCategory: "固态电池隔膜" }],
  "300576.SZ": [{ category: "半导体材料", subCategory: "光刻胶（G/I线成熟）" }],
  "300655.SZ": [{ category: "半导体材料", subCategory: "光刻胶（G/I线成熟）" }],
  "300666.SZ": [{ category: "半导体材料", subCategory: "溅射靶材" }],
  "300750.SZ": [{ category: "固态电池", subCategory: "固态电池（整体）" }, { category: "储能", subCategory: "储能电池" }],
  "300757.SZ": [{ category: "CPO", subCategory: "封装/耦合设备" }],
  "300769.SZ": [{ category: "锂电池", subCategory: "磷酸铁锂正极" }],
  "300772.SZ": [{ category: "绿色能源（风电）", subCategory: "风电整机" }],
  "301095.SZ": [{ category: "半导体材料", subCategory: "EDA软件" }],
  "301165.SZ": [{ category: "CPO", subCategory: "CPO交换机" }],
  "301269.SZ": [{ category: "半导体材料", subCategory: "EDA软件" }],
  "301358.SZ": [{ category: "锂电池", subCategory: "磷酸铁锂正极" }],
  "600183.SH": [{ category: "PCB", subCategory: "覆铜板（CCL）" }],
  "600206.SH": [{ category: "半导体材料", subCategory: "溅射靶材" }],
  "600458.SH": [{ category: "绿色能源（风电）", subCategory: "风电叶片" }],
  "600584.SH": [{ category: "半导体材料", subCategory: "先进封装（封测）" }],
  "600641.SH": [{ category: "半导体设备", subCategory: "离子注入" }],
  "600711.SH": [{ category: "能源金属", subCategory: "镍" }],
  "600884.SH": [{ category: "锂电池", subCategory: "负极材料" }],
  "603019.SH": [{ category: "AI算力", subCategory: "AI服务器" }],
  "603200.SH": [{ category: "固态电池", subCategory: "氧化物电解质" }],
  "603228.SH": [{ category: "PCB", subCategory: "汽车电子PCB" }],
  "603650.SH": [{ category: "半导体材料", subCategory: "光刻胶（KrF/ArF高端）" }],
  "603690.SH": [{ category: "半导体设备", subCategory: "清洗设备" }],
  "603799.SH": [{ category: "能源金属", subCategory: "钴" }, { category: "能源金属", subCategory: "镍" }],
  "603920.SH": [{ category: "PCB", subCategory: "汽车电子PCB" }],
  "603993.SH": [{ category: "能源金属", subCategory: "钴" }],
  "605358.SH": [{ category: "半导体材料", subCategory: "半导体硅片" }],
  "920185.BJ": [{ category: "锂电池", subCategory: "负极材料" }],
}
